services:
  - type: web
    name: medicore-backend
    runtime: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    envVars:
      - key: APP_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: "7"
      - key: ALLOWED_ORIGINS
        value: https://remarkable-salmiakki-62079a.netlify.app/
      - key: DATABASE_URL
        value: sqlite:///./medicore.db
